#!/usr/bin/env python3
"""Regenerates tests/generated/state_cases.bas from tests/state_cases.json.

The .bas module (Type=StaticCode) exposes GetStateCases so the on-device
runner UIStateTestRunner.bas executes the SAME cases as the Python suite
(tests/test_state.py). Run this after editing state_cases.json, then copy
UIStateTestRunner.bas, StateProbe.bas and state_cases.bas into a B4A test
project (see tests/README.md).
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'generated', 'state_cases.bas')


def emit_value(v):
    if v is None:
        return 'Null'
    if isinstance(v, bool):
        return 'True' if v else 'False'
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return str(v)
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, dict):
        inner = ', '.join('%s: %s' % (json.dumps(k), emit_value(val))
                          for k, val in v.items())
        return 'CreateMap(%s)' % inner
    if isinstance(v, list):
        inner = ', '.join(emit_value(x) for x in v)
        return 'Array As Object(%s)' % inner
    raise TypeError('unsupported value: %r' % (v,))


def emit_case(idx, case):
    lines = ['    Dim c%d As Map' % idx, '    c%d.Initialize' % idx]
    for key, value in case.items():
        lines.append('    c%d.Put("%s", %s)' % (idx, key, emit_value(value)))
    lines.append('    cases.Add(c%d)' % idx)
    return lines


def main():
    with open(os.path.join(HERE, 'state_cases.json'), encoding='utf-8') as f:
        data = json.load(f)

    out = [
        'B4A=true',
        'Group=Default Group',
        'ModulesStructureVersion=1',
        'Type=StaticCode',
        'Version=13.5',
        '@EndOfDesignText@',
        "' Generated by tests/generate_state_cases.py from tests/state_cases.json.",
        "' Do not edit by hand. Run: python3 tests/generate_state_cases.py",
        "' Supplies the shared UIState cases to UIStateTestRunner.bas (on-device state tests).",
        '',
        'Sub Process_Globals',
        'End Sub',
        '',
        'Public Sub GetStateCases As List',
        '    Dim cases As List',
        '    cases.Initialize',
    ]
    for i, case in enumerate(data['stateCases']):
        out.extend(emit_case(i + 1, case))
    out.append('    Return cases')
    out.append('End Sub')
    out.append('')

    # Exactly one UTF-8 BOM, CRLF line endings, like every repo .bas.
    text = chr(0xFEFF) + (chr(13) + chr(10)).join(out)
    with open(OUT, 'wb') as f:
        f.write(text.encode('utf-8'))
    print('wrote', OUT, '(%d state cases)' % len(data['stateCases']))
    return 0


if __name__ == '__main__':
    sys.exit(main())
